name: ambatukam

on:
  workflow_dispatch:

jobs:
  ambatukam:
    runs-on: ubuntu-22.04
    steps:
      - name: setup
        run: |
          sudo apt update -y
          sudo apt install tmate -y
          git config --global user.name "linastorvaldz"
          git config --global user.email "creamylofly@gmail.com"

      - name: Generate tmate ssh link
        run: |
          tmate -F
